/* config_host/config_wasm_strip.h.  Generated from config_wasm_strip.h.in by configure.  */
#ifndef CONFIG_FEATURE_WASM_STRIP_H
#define CONFIG_FEATURE_WASM_STRIP_H

#define ENABLE_WASM_STRIP_ACCESSIBILITY 1
#define ENABLE_WASM_STRIP_WRITER 1
#define ENABLE_WASM_STRIP_CALC 1
#define ENABLE_WASM_STRIP_CANVAS 1
#define ENABLE_WASM_STRIP_CHART 0
#define ENABLE_WASM_STRIP_DBACCESS 1
#define ENABLE_WASM_STRIP_EPUB 1
#define ENABLE_WASM_STRIP_EXTRA 1
#define ENABLE_WASM_STRIP_GUESSLANG 1
#define ENABLE_WASM_STRIP_HUNSPELL 0
#define ENABLE_WASM_STRIP_PINGUSER 1
#define ENABLE_WASM_STRIP_PREMULTIPLY 1
#define ENABLE_WASM_STRIP_RECENT 1
#define ENABLE_WASM_STRIP_RECOVERYUI 1
#define ENABLE_WASM_STRIP_SPLASH 1
#define ENABLE_WASM_STRIP_SWEXPORTS 1
#define ENABLE_WASM_STRIP_SCEXPORTS 1

#endif
